services:
  backend:
    image: fabiola/hello:latest
    restart: always
    ports:
      - 8081:8080
    environment:
      - POSTGRES_DB=example
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data # C:var
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=root
      #       POSTGRES_PASSWORD: "root"
    expose:
      - 5432
volumes:
  db-data:
networks:
  spring-postgres: